# Translations template for nova_powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 3.0.0.0rc2.dev10\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-10-07 02:04-0400\n"
"PO-Revision-Date: 2016-10-07 02:04-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.4\n"

#: nova_powervm/virt/powervm/driver.py:1548
msgid "Live migration timed out. Aborting migration"
msgstr "A migração em tempo real atingiu o tempo limite. Interrompendo a migração"

#: nova_powervm/virt/powervm/live_migration.py:331
msgid "Live migration failed."
msgstr "A migração em tempo real falhou."

#: nova_powervm/virt/powervm/live_migration.py:385
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "A recuperação da migração falhou com o erro: %s"

#: nova_powervm/virt/powervm/live_migration.py:413
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"A interrupção da migração em tempo real falhou. Este é sem bloqueio. A exceção está "
"registrada abaixo."

#: nova_powervm/virt/powervm/vif.py:106
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "O envio de eventos VIF customizados falhou.  %s"

#: nova_powervm/virt/powervm/vif.py:316
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Não é possível desconectar VIF com MAC %(mac)s para instância %(inst)s."

#: nova_powervm/virt/powervm/vm.py:646
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "A exclusão da máquina virtual falhou: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:258
#, python-format
msgid "Disk %s not found during resize."
msgstr "O disco %s não foi localizado durante o redimensionamento."

#: nova_powervm/virt/powervm/disk/ssp.py:331
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "A verificação de erro para o armazenamento compartilhado. exception=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Não foi possível atualizar o NVRAM: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"Não é possível remover VIFs da instância %(inst)s porque o sistema não está em um "
"estado correto.  O motivo relatado pelo sistema é: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"Não é possível criar VIF(s) para a instância %(sys)s.  A VM estava em um estado em que "
"plugar o VIF não é aceitável.  O motivo do sistema é: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Erro ao aguardar o VIF ser criado para a instância %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Falha da conexão de VIF para o retorno de chamada no evento %(event)s para a instância %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Não é possível armazenar o NVRAM para a instância %(name)s. Exceção: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Não é possível excluir o NVRAM para a instância %(name)s. Exceção: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:221
#: nova_powervm/virt/powervm/volume/vscsi.py:334
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Não é possível remover volumes da máquina virtual: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:223
#: nova_powervm/virt/powervm/volume/vscsi.py:336
#, python-format
msgid "Error: %s"
msgstr "Erro: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:515
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Os mapeamentos não puderam localizar um VIOS adequado. Os mapeamentos de porta foram %s."

# ENGL1SH_VERS10N 37135_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV132AAP001 2
